- hosts: all
  become: yes
  vars:
    deploy_env: "{{ deploy_env | default('prod') }}"
    repo_name: "{{ repo_name | default('prod-stack') }}"
    repo_dest: "/home/{{ ansible_user }}/{{ repo_name }}"

  tasks:
    - name: Ensure required packages are installed
      apt:
        name: ['podman', 'podman-compose', 'python3-pip', 'git', 'unzip', 'jq']
        state: present
        update_cache: yes
    
    - name: Download AWS CLI v2 bundled installer
      get_url:
        url: "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip"
        dest: "/tmp/awscliv2.zip"
        mode: '0644'

    - name: Unzip AWS CLI v2 installer
      unarchive:
        src: "/tmp/awscliv2.zip"
        dest: "/tmp"
        remote_src: yes

    - name: Run AWS CLI v2 installer
      shell: |
        ./aws/install --update
      args:
        chdir: /tmp
        creates: /usr/local/bin/aws


    - name: Write out .env file from vault
      template:
        src: templates/env.j2
        dest: "{{ repo_dest }}/.env"
        mode: 0600

    - name: Ensure backups directory exists
      file:
        path: "{{ repo_dest }}/backups"
        state: directory
        owner: "{{ ansible_user }}"
        mode: '0755'

    - name: Schedule daily S3 upload at 2AM
      cron:
        name: "Upload latest pg_dump to S3"
        user: "{{ ansible_user }}"
        minute: "0"
        hour: "2"
        job: >
          set -a && . {{ repo_dest }}/.env && set +a &&
          /usr/local/bin/aws s3 cp $(ls -t {{ repo_dest }}/backups/*.dump 2>/dev/null | head -n1) s3://$S3_BUCKET/ || echo "No dump to upload"

    - name: Check for docker-compose.override.yml.j2 template
      stat:
        path: "templates/docker-compose.override.yml.j2"
      register: override_compose
      delegate_to: localhost

    - name: Render docker-compose.override.yml if template exists
      template:
        src: templates/docker-compose.override.yml.j2
        dest: "{{ repo_dest }}/docker-compose.override.yml"
        mode: 0644
      when: override_compose.stat is defined and override_compose.stat.exists

    - name: Check for Caddyfile.j2 template
      stat:
        path: "templates/Caddyfile.j2"
      register: caddy_template
      delegate_to: localhost

    - name: Render Caddyfile from vault if template exists
      template:
        src: templates/Caddyfile.j2
        dest: "{{ repo_dest }}/caddy/Caddyfile"
        mode: 0644
      when: caddy_template.stat is defined and caddy_template.stat.exists

    - name: Allow docker.io as default registry for Podman
      become: true
      lineinfile:
        path: /etc/containers/registries.conf
        regexp: '^unqualified-search-registries ='
        line: 'unqualified-search-registries = ["docker.io"]'

    - name: Launch services
      shell: |
        cd {{ repo_dest }}
        podman-compose --env-file .env up -d
