- hosts: all
  become: yes
  vars:
    deploy_env: "{{ deploy_env | default('prod') }}"
    repo_name: "{{ repo_name | default('prod-stack') }}"
    repo_dest: "/home/{{ ansible_user }}/{{ repo_name }}"

  tasks:
    - name: Ensure required packages are installed
      apt:
        name: ['podman', 'podman-compose', 'python3-pip', 'git']
        state: present
        update_cache: yes

    - name: Write out .env file from vault
      template:
        src: templates/env.j2
        dest: "{{ repo_dest }}/.env"
        mode: 0600

    - name: Check for docker-compose.override.yml.j2 template
      stat:
        path: "templates/docker-compose.override.yml.j2"
      register: override_compose

    - name: Render docker-compose.override.yml if template exists
      template:
        src: templates/docker-compose.override.yml.j2
        dest: "{{ repo_dest }}/docker-compose.override.yml"
        mode: 0644
      when: override_compose.stat.exists

    - name: Check for Caddyfile.j2 template
      stat:
        path: "templates/Caddyfile.j2"
      register: caddy_template

    - name: Render Caddyfile from vault if template exists
      template:
        src: templates/Caddyfile.j2
        dest: "{{ repo_dest }}/caddy/Caddyfile"
        mode: 0644
      when: caddy_template.stat.exists

    - name: Allow docker.io as default registry for Podman
      become: true
      lineinfile:
        path: /etc/containers/registries.conf
        regexp: '^unqualified-search-registries ='
        line: 'unqualified-search-registries = ["docker.io"]'

    - name: Launch services
      shell: |
        cd {{ repo_dest }}
        podman-compose --env-file .env up -d
